# Juan Zurita
Computer Science Student at Brigham Young University - Idaho | Online TA for WDD 230

<div id="webaddress">
    <a href="mailto:juanzurita@byui.edu">juanzurita@byui.edu</a> | 
    <a href="https://github.com/juan-zv">My GitHub page</a> | 
    <a href="https://www.linkedin.com/in/juanzuritavasquez/">My LinkedIn page</a>
</div>


## Currently

**Online Teacher Assistant for WDD 230**  
Rexburg, ID | Brigham Young University-Idaho    `Apr 2023-Present`

- Provided guidance and support to 20+ students in web development using HTML, CSS, and JavaScript.
- Guided students to achieve proficiency in creating responsive, well-designed, and interactive web pages using HTML, CSS, and JavaScript.
- Assisted students in understanding and implementing web development concepts, troubleshoot coding issues, and contribute to a collaborative learning environment.


## Education

**Brigham Young University-Idaho**  
Rexburg, ID  
Bachelor of Science Computer Science  
Expected Graduation Date: __Apr 2026__
- 	Relevant Coursework: Web Frontend I, Data Science Programming, Applied Programming, etc.
- OOP, Database handling, Optimization, Web Development.
- GPA __3.78/4.0__

**Certificate of Computer Programming**    `Aug 2023`
- Coursework: Algorithm Design, Data Structures, Object Oriented Programming, Work Methodology.
- Emphasis in Software Development as a service while being part of a team.


## Experience

**International Services Processor**  
Rexburg, ID | Brigham Young University-Idaho    `Nov 2022-Aug 2023`

- Efficiently handled walk-ins, phone calls, and emails, providing information and directing students to appropriate departments.
- Assisted students with administrative processes and immigration-related questions, offering guidance and facilitating necessary paperwork.
- Maintained organized records, schedule appointments, and perform general administrative tasks with attention to detail and multitasking abilities.


### Volunteer Service

**Full-time Volunteer Representative**  
Santa Cruz, Bolivia | The Church of Jesus Christ of Latter-day Saints    `Jan 2020-Jan 2022`

- Taught English as a second language for groups of 5-10 people.
- Served as an executive secretary, coordinating travel and logistics for volunteers.
- Conducted training and goal-setting sessions, enhancing the effectiveness of volunteer efforts.
- Led and trained other volunteers as trainer, district leader, zone leader.


## Personal Projects

- **Juan Zurita Portfolio**: Static web page designed to showcase my projects and provide a professional bio.
- **U&I Ride**: Mobile app concept aimed at optimizing ride-sharing services in the Rexburg – Utah area.
- **Estudio + Fe**: Web application focused on enhancing scripture cross-referencing and note-taking capabilities for a wider audience.


## Skills and Interests

### Programming Languages
- Proficient in: Python, C#, JavaScript.
- Familiar with: Dart, Kotlin, Swift, Rust.
### Web and Mobile Development
- Experienced in: SCSS, Firebase, Flutter, React, and React Native.
- Familiar with: Android Studio and XCode.
### Tools and Technologies
- Skilled in SCRUM, Git, Web and Mobile layout design.




<!-- ### Footer

Last updated: Apr 2024 -->